# Generated by Django 4.1 on 2022-09-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=11, null=True)),
                ('nombre_candidato', models.CharField(max_length=200, null=True)),
                ('puesto_aspiracion', models.CharField(max_length=200, null=True)),
                ('departamento', models.CharField(max_length=200, null=True)),
                ('salario_aspiracion', models.FloatField(null=True)),
                ('principales_competencias', models.CharField(max_length=200, null=True)),
                ('principales_capacitaciones', models.CharField(max_length=200, null=True)),
                ('experiencia_laboral', models.CharField(max_length=200, null=True)),
                ('recomendacion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('nivel', models.CharField(choices=[('Grado', 'Grado'), ('Post-grado', 'Post-grado'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado'), ('Tecnico', 'Tecnico')], max_length=200, null=True)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_final', models.DateTimeField(null=True)),
                ('institucion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=11, null=True)),
                ('nombre_empleado', models.CharField(max_length=200, null=True)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('departamento', models.CharField(max_length=200, null=True)),
                ('puesto', models.CharField(max_length=200, null=True)),
                ('salario', models.FloatField(null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_Laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, null=True)),
                ('puesto_ocupado', models.CharField(max_length=200, null=True)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_final', models.DateTimeField(null=True)),
                ('salario', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_idioma', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=200, null=True)),
                ('nivel_riesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=200, null=True)),
                ('salario_minimo', models.FloatField(null=True)),
                ('salario_maximo', models.FloatField(null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=200, null=True)),
            ],
        ),
    ]
