# Generated by Django 4.1 on 2022-09-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudrh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='principales_capacitaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudrh.capacitaciones'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='principales_competencias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudrh.competencias'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='puesto_aspiracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudrh.puestos'),
        ),
    ]
