# Generated by Django 4.1 on 2022-09-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudrh', '0003_alter_capacitaciones_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='experiencia_laboral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudrh.experiencia_laboral'),
        ),
    ]
