# Generated by Django 4.1 on 2022-09-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudrh', '0004_alter_candidatos_experiencia_laboral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='nombre_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='salario',
        ),
        migrations.AddField(
            model_name='empleados',
            name='candidatos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudrh.candidatos'),
        ),
    ]
