# Generated by Django 4.1 on 2022-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrh', '0007_rename_candidatos_empleados_candidato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='codigo_empleado',
            field=models.FloatField(null=True),
        ),
    ]
