# Generated by Django 4.1 on 2022-09-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrh', '0008_empleados_codigo_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='codigo_empleado',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
