# Generated by Django 4.1.1 on 2022-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrh', '0011_remove_experiencia_laboral_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
