# Generated by Django 4.1.1 on 2022-09-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudrh', '0012_empleados_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='fecha_inicio',
            new_name='fecha_iniciod',
        ),
    ]
